---
extends: default

rules:
  line-length: disable
  truthy: disable

ignore: |
  # yamllint does not understand erb template
  .kitchen.local.yml
  .kitchen/
  extra_roles/
  # securityconfig is not managed by us
  files/test/securityconfig
