---
roles:
  - name: trombik.sysctl
  - name: trombik.java
  - name: trombik.freebsd_pkg_repo
  - name: trombik.x509_certificate
  - name: trombik.opensearch_dashboards
  - name: trombik.haproxy
collections:
  - name: community.general
  - name: ansible.posix
