---

- name: Install opensearch_extra_packages
  ansible.builtin.apt:
    name: "{{ opensearch_extra_packages }}"
    state: present

- name: Install gpg
  ansible.builtin.apt:
    name: gpg
    state: present

- name: "Include install-src.yml"
  include: "install-src.yml"
