---

- name: Restart opensearch
  service:
    name: "{{ opensearch_service }}"
    state: restarted
  notify: Wait for opensearch to start in handler

- name: Wait for opensearch to start in handler
  wait_for:
    host: "{{ opensearch_http_host }}"
    port: "{{ opensearch_http_port }}"
